### ISSUE TITLE
how to set the default formation?

### ISSUE THREAD

**Issue by dan-da** [yukihirop/ultraman#37]
Is there some equivalent to the .foreman file for setting default options?   I tried both .foreman and .ultraman but it doesn't seem to read either.

from https://ddollar.github.io/foreman/
```
DEFAULT OPTIONS
If a .foreman file exists in the current directory, default options will be read from it. This file should be in YAML format with the long option name as keys. Example:

formation: alpha=0,bravo=1
port: 15000
```

**Comment by yukihirop** [comment]
@dan-da 

> If a .foreman file exists in the current directory, default options will be read from it. This file should be in YAML format with the long option name as keys. Example:

`ultraman` doesn't read .ultraman even if it exists. sorry...
I would be grateful if you could send me a PR if you like. 🙇‍♂️
