### ISSUE TITLE
env vars are not consistent

### ISSUE THREAD

**Issue by xxx** [yukihirop/ultraman#53]
Heya, thanks for making this project!

### Steps to reproduce
The line from our procfile is `web: bundle exec puma -p $PORT -C ./config/puma.rb`, and a .env with `PORT=3000`, we see inconsistent results when running.

We're running via `ultraman start`.

### Expected behavior
The server starts on port 3000

### Actual behavior
The server starts on inconsistent ports, but always a multiple of 100, and always near the correct value of 3000. 3100 and 3200 are common values. Sometimes it _is_ correct with 3000 as well.

e.g.

```
11:08:01 web.1              | 2023-12-11T19:08:01.393Z pid=103762 tid=2f5u INFO: Sidekiq 7.2.0 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>nil}
11:08:01 web.1              | [103762] * Listening on http://0.0.0.0:3100 <-------------------- 
11:08:01 web.1              | [103762] Use Ctrl-C to stop
11:08:01 web.1              | [103762] - Worker 0 (PID: 104330) booted in 0.01s, phase: 0
11:08:01 web.1              | [103762] - Worker 1 (PID: 104334) booted in 0.01s, phase: 0
11:08:01 web.1              | [103762] - Worker 2 (PID: 104341) booted in 0.01s, phase: 0
11:08:01 web.1              | [103762] - Worker 3 (PID: 104354) booted in 0.0s, phase: 0
```

Stopping the server, waiting a minute or so, and re-running then puts it on a different port:

`11:10:14 web.1              | [108858] * Listening on http://0.0.0.0:3200`

Running the `bundle exec` line directly in a shell always starts the server on port 3000 as expected. Other foreman implementations also work as expected.

If `-p $PORT` is not specified in the procfile, the server consistently starts on port 9292, which is the expected default.

If we hardcode `-p 3000` in the procfile, the server starts consistently on port 3000.

### System configuration
**ultraman version**: 0.3.0

**Rust version**: 1.74.1

**Comment by yukihirop** [comment]
@xxx 

Thanks for the report.
We will fix it.🙇‍♂️
